language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1

before_install:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install
